# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./devdata.sql:/docker-entrypoint-initdb.d/devdata.sql

  kana-db:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
